dist: trusty
language: c
sudo: false
env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=6.3
    - RACKET_VERSION=6.6
    - RACKET_VERSION=6.9
    - RACKET_VERSION=6.12
    - RACKET_VERSION=7.0
    - RACKET_VERSION=7.3
    - RACKET_VERSION=7.4
    - RACKET_VERSION=7.5
    - RACKET_VERSION=7.6
    - RACKET_VERSION=HEAD
    - RACKET_VERSION=HEADCS

matrix:
  allow-failures:
    - env: RACKET_VERSION=HEAD
    - env: RACKET_VERSION=HEADCS
  fast_finish: true

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git 
  - cat travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

script:
 - cd ..
 - travis_retry raco pkg install --deps search-auto https://github.com/ausimian/racket-quickcheck.git
 - raco test quickcheck
 - raco quickcheck quickcheck/private/test/main.rkt
